version: '3.8'

services:
#  frontend:
#    build: ./frontend
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    command: [ "npm", "start" ]
#    env_file:
#      - ./frontend/.env.development

  backend:
    build: ./OneProject
    ports:
      - "8080:8080"
