name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - master  # master 브랜치에 push될 때 자동으로 실행

jobs:
  deploy:
    runs-on: self-hosted  # self-hosted runner를 사용하여 EC2에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Java 17로 설정
          distribution: 'adoptopenjdk'  # AdoptOpenJDK 사용 (Java 17 버전)

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        run: ./gradlew build -x test  # Gradle로 빌드 (테스트 제외)

      - name: Copy .jar to EC2
        run: |
          # EC2 인스턴스로 .jar 파일을 복사
          scp -i ${{ secrets.EC2_KEY }} OneProject/build/libs/OneProject-0.0.1-SNAPSHOT.jar ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/deploy/
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}  # GitHub Secrets에 저장된 EC2 키 파일
          EC2_IP: ${{ secrets.EC2_IP }}    # GitHub Secrets에 저장된 EC2 IP 주소

      - name: SSH into EC2 and run the application
        run: |
          # EC2에 SSH로 접속하여 Spring Boot 애플리케이션 실행
          ssh -i ${{ secrets.EC2_KEY }} ec2-user@${{ secrets.EC2_IP }} << 'EOF'
            # EC2 서버 내 deploy 디렉터리로 이동
            cd /home/ec2-user/deploy
            # 기존 실행 중인 애플리케이션이 있다면 종료
            pkill -f 'java -jar your-spring-boot-app.jar' || true
            # 새로운 Spring Boot 애플리케이션 실행
            nohup java -jar your-spring-boot-app.jar > app.log 2>&1 &
          EOF
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
          EC2_IP: ${{ secrets.EC2_IP }}
