name: CI/CD for Spring Boot Application

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Deploy to EC2
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # .jar 파일을 EC2로 복사
          scp -i $EC2_PRIVATE_KEY target/your-spring-boot-app.jar $EC2_USER@$EC2_HOST:/home/ubuntu

          # EC2에서 Spring Boot 애플리케이션 실행 (이미 실행 중인 인스턴스가 있으면 종료)
          ssh -i $EC2_PRIVATE_KEY $EC2_USER@$EC2_HOST << 'EOF'
            pkill -f your-spring-boot-app.jar || true
            nohup java -jar /home/ubuntu/your-spring-boot-app.jar > /home/ubuntu/app.log 2>&1 &
          EOF
